from datetime import datetime, timezone
from enum import Enum
from typing import Any, Dict, List, Optional
from pydantic import BaseModel, Field, model_validator


class EvidenceType(str, Enum):
    """Semantic category of a granular physics evidence unit."""
    DEFINITION = "DEFINITION"
    CONCEPT_EXPLANATION = "CONCEPT_EXPLANATION"
    EXPOSITION = "EXPOSITION"
    DERIVATION = "DERIVATION"
    WORKED_EXAMPLE = "WORKED_EXAMPLE"
    THEOREM_PRINCIPLE = "THEOREM_PRINCIPLE"
    LAW = "LAW"
    FORMULA_EXPLANATION = "FORMULA_EXPLANATION"
    FIGURE_EXPLANATION = "FIGURE_EXPLANATION"
    PROBLEM = "PROBLEM"
    SOLUTION = "SOLUTION"
    MOCK_QUESTION = "MOCK_QUESTION"


class SourceFidelityClass(str, Enum):
    """Explicit source fidelity classification for Phase 11.9.1."""
    SOURCE_VERBATIM = "SOURCE_VERBATIM"      # Verbatim text directly present in source (whitespace/hyphen normalized)
    SOURCE_VISUAL = "SOURCE_VISUAL"          # Scanned/image source verified visually (Feynman)
    SOURCE_DERIVED = "SOURCE_DERIVED"        # Mathematically structured/normalized from source (formulas, tables, steps)
    PROJECT_DERIVED = "PROJECT_DERIVED"      # Project created (taxonomy, statistics, relations)
    INDEX_METADATA = "INDEX_METADATA"        # Generated structural metadata about source


class FidelityMatchResult(str, Enum):
    """Outcome of independent source page verification (Phase 11.9.1)."""
    EXACT_MATCH = "EXACT_MATCH"
    NORMALIZED_MATCH = "NORMALIZED_MATCH"
    PARTIAL_MATCH = "PARTIAL_MATCH"
    NO_MATCH = "NO_MATCH"
    VISUAL_ONLY = "VISUAL_ONLY"
    EXTRACTION_UNCERTAIN = "EXTRACTION_UNCERTAIN"


class EvidenceTruthClassification(str, Enum):
    """Hard boundary classification between authentic source content and project metadata (Phase 11.9)."""
    SOURCE_EXACT = "SOURCE_EXACT"          # Content directly extracted verbatim from PDF
    SOURCE_VERBATIM = "SOURCE_VERBATIM"    # Verbatim text directly present in source
    SOURCE_VISUAL = "SOURCE_VISUAL"        # Scanned/image source verified visually
    SOURCE_DERIVED = "SOURCE_DERIVED"      # Mathematically structured/normalized from source
    INDEX_METADATA = "INDEX_METADATA"      # Generated structural metadata describing source
    PROJECT_DERIVED = "PROJECT_DERIVED"    # Generated by project from evidence (taxonomy, relations)
    VERIFICATION_DERIVED = "VERIFICATION_DERIVED"  # Created during verification/adjudication


class TaxonomyMappingQuality(str, Enum):
    """Classification of precision for project-derived taxonomy mappings (Phase 11.9)."""
    DIRECT = "DIRECT"                      # Exact one-to-one mapping to target JEE node
    RELATED = "RELATED"                    # Closely related concept within same chapter/domain
    BROAD_CHAPTER_ONLY = "BROAD_CHAPTER_ONLY" # General topic mapping at chapter root level
    UNCERTAIN = "UNCERTAIN"                # Tentative or ambiguous mapping


class ExtractionQuality(str, Enum):
    """Assessment of text extraction reliability for a page or fragment."""
    EXCELLENT = "EXCELLENT"            # Clean digital text streams with math symbols intact
    GOOD = "GOOD"                      # Readable text with minor spacing or OCR quirks
    DEGRADED = "DEGRADED"              # Poor text stream requiring heuristic recovery
    NORMALIZED_FONT = "NORMALIZED_FONT"# Text recovered via font-table offset decode (e.g. HCV2)
    VECTORIZED_GLYPHS = "VECTORIZED_GLYPHS"  # Outlined vector glyphs without digital text font stream
    EMPTY = "EMPTY"                    # Blank page, cover, or purely unextractable
    VISUALLY_EXTRACTED_FROM_SOURCE = "VISUALLY_EXTRACTED_FROM_SOURCE"  # Scanned or image-only page verified visually



class PageEvidenceRecord(BaseModel):
    """Deterministic page-level audit record for each page across all corpus PDFs."""
    source_id: str = Field(..., description="Unique source identifier")
    pdf_page_number: int = Field(..., ge=1, description="1-based PDF file page index")
    printed_page_number: Optional[str] = Field(None, description="Printed header/footer page number if identifiable")
    extraction_quality: ExtractionQuality = Field(..., description="Classification of text extraction")
    text_length: int = Field(..., ge=0, description="Extracted character count")
    is_corrupted: bool = Field(False, description="Whether text stream appears corrupted or garbled")
    has_equations: bool = Field(False, description="Whether page contains mathematical expressions")
    has_figures: bool = Field(False, description="Whether page contains illustrations or diagrams")
    has_tables: bool = Field(False, description="Whether page contains data or classification tables")
    has_examples: bool = Field(False, description="Whether page contains worked/illustrative examples")
    has_exercises_problems: bool = Field(False, description="Whether page contains end-of-chapter or practice questions")
    section_or_chapter_heading: Optional[str] = Field(None, description="Identified chapter or section header")
    text_snippet: Optional[str] = Field(None, description="Representative ~150-char diagnostic text preview")


class SourceEvidenceRecord(BaseModel):
    """Granular semantic evidence unit extracted verbatim from a source page range."""
    evidence_id: str = Field(..., description="Deterministic unique evidence ID")
    source_id: str = Field(..., description="Parent source document ID")
    source_segment_id: Optional[str] = Field(None, description="Parent coarse segment ID")
    page_start: int = Field(..., ge=1, description="Starting 1-based PDF page")
    page_end: int = Field(..., ge=1, description="Ending 1-based PDF page")
    section_or_chapter: str = Field(..., description="Section title or chapter heading")
    section: Optional[str] = Field(None, description="Alias for section_or_chapter")
    evidence_type: EvidenceType = Field(..., description="Type of physics evidence")
    content_text: str = Field(..., description="Exact raw/extracted source text (unmodified)")
    extraction_quality: ExtractionQuality = Field(ExtractionQuality.GOOD)
    extraction_method: Optional[str] = Field("DIGITAL_TEXT", description="Method used: DIGITAL_TEXT, FONT_DECODED, VISUALLY_VERIFIED, OCR_RECOVERED")
    taxonomy_node_ids: List[str] = Field(default_factory=list, description="Authoritative taxonomy node IDs")
    figure_refs: List[str] = Field(default_factory=list, description="Associated figure evidence IDs")
    equation_refs: List[str] = Field(default_factory=list, description="Associated formula evidence IDs")
    problem_number: Optional[str] = Field(None, description="Problem label/number if applicable")
    parent_evidence_id: Optional[str] = Field(None, description="Parent evidence unit ID if nested")
    child_evidence_ids: List[str] = Field(default_factory=list, description="Child evidence unit IDs")
    provenance: Dict[str, Any] = Field(default_factory=dict, description="Bibliographic citation & page bounds")
    truth_classification: EvidenceTruthClassification = Field(
        default=EvidenceTruthClassification.SOURCE_EXACT,
        description="Hard distinction: SOURCE_EXACT vs INDEX_METADATA vs PROJECT_DERIVED vs VERIFICATION_DERIVED",
    )
    mapping_quality: TaxonomyMappingQuality = Field(
        default=TaxonomyMappingQuality.DIRECT,
        description="Quality of taxonomy mapping: DIRECT, RELATED, BROAD_CHAPTER_ONLY, UNCERTAIN",
    )
    fidelity_class: SourceFidelityClass = Field(
        default=SourceFidelityClass.SOURCE_VERBATIM,
        description="Phase 11.9.1 Fidelity class: SOURCE_VERBATIM, SOURCE_VISUAL, SOURCE_DERIVED, PROJECT_DERIVED, INDEX_METADATA",
    )
    fidelity_match: Optional[FidelityMatchResult] = Field(None, description="Independent verification match result")
    source_page_hash: Optional[str] = Field(None, description="SHA-256 fingerprint of normalized source page text")
    evidence_content_hash: Optional[str] = Field(None, description="SHA-256 fingerprint of normalized evidence text")

    @model_validator(mode="before")
    def set_section_alias(cls, values: Any) -> Any:
        if isinstance(values, dict):
            if "section" in values and "section_or_chapter" not in values:
                values["section_or_chapter"] = values["section"]
            elif "section_or_chapter" in values and "section" not in values:
                values["section"] = values["section_or_chapter"]

            # Content text normalization
            if "content_text" not in values:
                if "clean_text" in values and values["clean_text"]:
                    values["content_text"] = values["clean_text"]
                elif "raw_text" in values and values["raw_text"]:
                    values["content_text"] = values["raw_text"]

            # Quality normalization
            q = values.get("extraction_quality")
            if q in ("HIGH", "EXCELLENT"):
                values["extraction_quality"] = ExtractionQuality.EXCELLENT
            elif q in ("MEDIUM", "GOOD"):
                values["extraction_quality"] = ExtractionQuality.GOOD
            elif q == "LOW":
                values["extraction_quality"] = ExtractionQuality.DEGRADED
        return values

    @model_validator(mode="after")
    def validate_pages(self) -> "SourceEvidenceRecord":
        if self.page_start > self.page_end:
            raise ValueError(f"page_start ({self.page_start}) cannot exceed page_end ({self.page_end})")
        return self


class FormulaEvidenceRecord(BaseModel):
    """Granular formula inventory item grounded in source evidence."""
    formula_id: str = Field(..., description="Deterministic formula ID")
    normalized_latex: str = Field(..., description="LaTeX representation of formula")
    source_id: str = Field(..., description="Originating source ID")
    pages: List[int] = Field(default_factory=list, description="Pages where formula appears")
    surrounding_explanatory_evidence_id: Optional[str] = Field(None, description="Pointer to evidence record")
    variables: Dict[str, str] = Field(default_factory=dict, description="Symbol -> definition as stated in source")
    explicitly_stated_assumptions: List[str] = Field(default_factory=list, description="Assumptions stated by source")
    explicitly_stated_conditions: List[str] = Field(default_factory=list, description="Conditions of validity")
    notation_or_convention: str = Field("STANDARD_SI", description="Notation or sign convention used")
    corroborating_source_ids: List[str] = Field(default_factory=list, description="Other sources containing same formula")
    conflict_references: List[str] = Field(default_factory=list, description="Disagreement IDs if conventions clash")
    extraction_confidence: float = Field(1.0, ge=0.0, le=1.0)
    taxonomy_node_ids: List[str] = Field(default_factory=list)
    truth_classification: EvidenceTruthClassification = Field(default=EvidenceTruthClassification.SOURCE_EXACT)
    fidelity_class: SourceFidelityClass = Field(default=SourceFidelityClass.SOURCE_DERIVED)
    fidelity_match: Optional[FidelityMatchResult] = Field(None)
    source_page_hash: Optional[str] = Field(None)


class DerivationEvidenceRecord(BaseModel):
    """Granular derivation sequence grounded in source evidence."""
    derivation_id: str = Field(..., description="Deterministic derivation ID")
    source_id: str = Field(..., description="Originating source ID")
    page_range: List[int] = Field(..., description="[start_page, end_page]")
    title: str = Field(..., description="Derivation topic/title")
    starting_assumptions: List[str] = Field(default_factory=list)
    starting_equations: List[str] = Field(default_factory=list)
    intermediate_steps: List[str] = Field(default_factory=list, description="Step-by-step mathematical reasoning")
    final_result: str = Field(..., description="Final derived equation in LaTeX")
    supporting_figures: List[str] = Field(default_factory=list)
    taxonomy_node_ids: List[str] = Field(default_factory=list)
    truth_classification: EvidenceTruthClassification = Field(default=EvidenceTruthClassification.SOURCE_EXACT)
    fidelity_class: SourceFidelityClass = Field(default=SourceFidelityClass.SOURCE_DERIVED)
    fidelity_match: Optional[FidelityMatchResult] = Field(None)
    source_page_hash: Optional[str] = Field(None)


class ExampleEvidenceRecord(BaseModel):
    """Source-grounded worked example."""
    example_id: str = Field(..., description="Deterministic example ID")
    source_id: str = Field(..., description="Originating source ID")
    page_range: List[int] = Field(..., description="[start_page, end_page]")
    title_or_label: str = Field("", description="Example number or title (e.g. Example 10.3)")
    title: Optional[str] = Field(None, description="Alternative alias for title_or_label")
    problem_statement: str = Field(..., description="Problem statement verbatim from source")
    source_method: str = Field(..., description="Method/solution steps from source")
    source_result: str = Field(..., description="Final result stated in source")
    relevant_figures: List[str] = Field(default_factory=list)
    taxonomy_node_ids: List[str] = Field(default_factory=list)
    truth_classification: EvidenceTruthClassification = Field(default=EvidenceTruthClassification.SOURCE_EXACT)
    fidelity_class: SourceFidelityClass = Field(default=SourceFidelityClass.SOURCE_DERIVED)
    fidelity_match: Optional[FidelityMatchResult] = Field(None)
    source_page_hash: Optional[str] = Field(None)

    @model_validator(mode="before")
    @classmethod
    def populate_title(cls, data: Any) -> Any:
        if isinstance(data, dict):
            if not data.get("title_or_label") and data.get("title"):
                data["title_or_label"] = data["title"]
            elif not data.get("title") and data.get("title_or_label"):
                data["title"] = data["title_or_label"]
        return data


class ProblemEvidenceRecord(BaseModel):
    """Source practice/exercise problem from textbook or question collection."""
    problem_id: str = Field(..., description="Deterministic problem ID")
    source_id: str = Field(..., description="Originating source ID")
    chapter_or_section: str = Field(...)
    page: int = Field(..., ge=1)
    printed_problem_number: str = Field(..., description="Problem number as printed in book")
    problem_statement: str = Field(..., description="Problem text verbatim from source")
    figures: List[str] = Field(default_factory=list)
    source_solution: Optional[str] = Field(None, description="Solution from book if present")
    source_answer: Optional[str] = Field(None, description="Answer key from book if present")
    taxonomy_node_ids: List[str] = Field(default_factory=list)
    difficulty_evidence: Optional[str] = Field(None, description="Difficulty indicators in source (e.g., * in Irodov)")
    extraction_confidence: float = Field(1.0, ge=0.0, le=1.0)
    truth_classification: EvidenceTruthClassification = Field(default=EvidenceTruthClassification.SOURCE_EXACT)
    fidelity_class: SourceFidelityClass = Field(default=SourceFidelityClass.SOURCE_VERBATIM)
    fidelity_match: Optional[FidelityMatchResult] = Field(None)
    source_page_hash: Optional[str] = Field(None)


class MockQuestionEvidenceRecord(BaseModel):
    """Granular evidence record for verified physics questions in JEE mock papers."""
    mock_question_id: str = Field(..., description="Deterministic mock question ID")
    source_id: str = Field(...)
    page: int = Field(..., ge=1)
    question_number: int = Field(..., ge=1, le=30, description="Strictly 1 to 30 for physics questions")
    subject: str = Field("PHYSICS", description="Enforced PHYSICS boundary")
    question_statement: str = Field(...)
    options: Dict[str, str] = Field(default_factory=dict)
    source_answer: Optional[str] = Field(None)
    source_solution: Optional[str] = Field(None)
    figures: List[str] = Field(default_factory=list)
    taxonomy_node_ids: List[str] = Field(default_factory=list)
    extraction_confidence: float = Field(1.0, ge=0.0, le=1.0)
    truth_classification: EvidenceTruthClassification = Field(default=EvidenceTruthClassification.SOURCE_EXACT)
    fidelity_class: SourceFidelityClass = Field(default=SourceFidelityClass.SOURCE_VERBATIM)
    fidelity_match: Optional[FidelityMatchResult] = Field(None)
    source_page_hash: Optional[str] = Field(None)


class FigureEvidenceRecord(BaseModel):
    """Source diagram or visual evidence record."""
    figure_id: str = Field(..., description="Deterministic figure ID")
    source_id: str = Field(...)
    page: int = Field(..., ge=1)
    parent_concept_or_problem_id: Optional[str] = Field(None)
    bounding_box: Optional[List[float]] = Field(None, description="[x0, y0, x1, y1] on page if detectable")
    caption: Optional[str] = Field(None, description="Figure caption extracted from page")
    relationship_to_text: str = Field("", description="How the figure connects to the physics argument")
    page_image_ref: Optional[str] = Field(None, description="Path or identifier for page visual")
    truth_classification: EvidenceTruthClassification = Field(default=EvidenceTruthClassification.SOURCE_EXACT)
    fidelity_class: SourceFidelityClass = Field(default=SourceFidelityClass.SOURCE_DERIVED)
    fidelity_match: Optional[FidelityMatchResult] = Field(None)
    source_page_hash: Optional[str] = Field(None)


class TaxonomyEvidenceBundle(BaseModel):
    """Complete retrieval payload for a requested taxonomy node."""
    taxonomy_node_id: str = Field(...)
    taxonomy_name: str = Field(...)
    corroborating_sources: List[str] = Field(default_factory=list)
    evidence_records: List[SourceEvidenceRecord] = Field(default_factory=list)
    source_evidence_records: List[SourceEvidenceRecord] = Field(default_factory=list, description="Strictly SOURCE_EXACT records")
    verbatim_records: List[SourceEvidenceRecord] = Field(default_factory=list, description="Strictly SOURCE_VERBATIM records")
    visual_records: List[SourceEvidenceRecord] = Field(default_factory=list, description="Strictly SOURCE_VISUAL records")
    derived_records: List[Any] = Field(default_factory=list, description="SOURCE_DERIVED records (formulas, derivations, etc.)")
    metadata_records: List[SourceEvidenceRecord] = Field(default_factory=list, description="INDEX_METADATA or PROJECT_DERIVED records")
    formulas: List[FormulaEvidenceRecord] = Field(default_factory=list)
    derivations: List[DerivationEvidenceRecord] = Field(default_factory=list)
    examples: List[ExampleEvidenceRecord] = Field(default_factory=list)
    problems: List[ProblemEvidenceRecord] = Field(default_factory=list)
    mock_questions: List[MockQuestionEvidenceRecord] = Field(default_factory=list)
    figures: List[FigureEvidenceRecord] = Field(default_factory=list)
    source_conflicts: List[Dict[str, Any]] = Field(default_factory=list)


class SourceEvidenceCoverageReport(BaseModel):
    """Comprehensive statistical and analytical report of the granular evidence layer."""
    report_id: str = Field(...)
    generated_at: datetime = Field(default_factory=lambda: datetime.now(timezone.utc))
    total_sources: int = Field(..., ge=1)
    total_source_pages: int = Field(..., ge=1)
    pages_successfully_indexed: int = Field(..., ge=1)
    pages_with_poor_or_vector_extraction: int = Field(0, ge=0)
    total_granular_evidence_records: int = Field(0, ge=0)
    total_formulas: int = Field(0, ge=0)
    total_derivations: int = Field(0, ge=0)
    total_examples: int = Field(0, ge=0)
    total_problems: int = Field(0, ge=0)
    total_mock_questions: int = Field(0, ge=0)
    total_figures: int = Field(0, ge=0)
    total_taxonomy_nodes: int = Field(..., ge=1)
    multi_source_nodes_count: int = Field(0, ge=0)
    single_source_nodes_count: int = Field(0, ge=0)
    no_evidence_nodes_count: int = Field(0, ge=0)
    extraction_uncertainties_count: int = Field(0, ge=0)
    unresolved_source_conflicts_count: int = Field(0, ge=0)
    evidence_counts_by_chapter: Dict[str, Dict[str, int]] = Field(default_factory=dict)
